{
  config,
  lib,
  pkgs,
  utils,
  ...
}: let
  inherit
    (lib)
    attrNames
    attrValues
    concatLists
    concatMap
    concatStringsSep
    filter
    filterAttrs
    hasSuffix
    literalExpression
    mapAttrsToList
    mkEnableOption
    mkIf
    mkMerge
    mkOption
    mkOptionDefault
    mkPackageOption
    optional
    types
    unique
    ;

  cfg = config.services.asterisk;
  asteriskLib = import ../lib {inherit lib;};
  inherit (asteriskLib) format secrets;
  moduleLib = import ./lib.nix {inherit lib;};

  paths = {
    template = "/etc/asterisk";
    runtime = "/run/asterisk";
    config = "/run/asterisk/config";
    state = "/var/lib/asterisk";
    spool = "/var/lib/asterisk/spool";
    log = "/var/log/asterisk";
    credentials = "/run/credentials/asterisk.service";
  };

  # directories below the state directory that Asterisk uses but does not
  # create; the service creates them, and the build-time check below its root
  stateDirectories =
    [
      "agi-bin"
      "keys"
    ]
    ++ map (dir: "spool/${dir}") [
      "voicemail"
      "monitor"
      "recording"
      "outgoing"
      "tmp"
      "meetme"
      "dictate"
      "system"
    ];

  # Read-only data: sounds, music on hold, documentation, static HTTP files.
  dataDir = pkgs.symlinkJoin {
    name = "asterisk-data";
    paths = ["${cfg.package}/var/lib/asterisk"] ++ cfg.sounds.packages;
  };

  fileNames = unique (
    attrNames cfg.settings
    ++ attrNames (filterAttrs (_: text: text != "") cfg.extraConfig)
    ++ attrNames (filterAttrs (_: incs: incs != []) cfg.includes)
  );

  syntaxFor = file:
    if cfg.syntax ? ${file}
    then removeAttrs cfg.syntax.${file} ["_module"]
    else format.syntaxFor file;

  renderWith = file: sections:
    format.render
    {
      syntax = syntaxFor file;
      inherit file;
      header =
        if hasSuffix ".conf" file
        then "Generated by NixOS (services.asterisk); changes will be overwritten."
        else null;
    }
    {
      inherit sections;
      includes = cfg.includes.${file} or [];
      extraConfig = cfg.extraConfig.${file} or "";
    };
  renderFile = file: renderWith file (cfg.settings.${file} or {});

  configFile = file: pkgs.writeText "asterisk-${lib.replaceStrings ["/"] ["-"] file}";

  generatedConfig = pkgs.linkFarm "asterisk-config" (
    map (file: {
      name = file;
      path = configFile file cfg.renderedFiles.${file};
    })
    fileNames
  );

  # the configuration the build-time check starts Asterisk with (see
  # pkgs/config-check): what it writes goes below @root@, it logs errors,
  # warnings and verbose messages, which say when it is ready, to one file,
  # and each credential is a throwaway certificate
  checkAsteriskConf = let
    conf = cfg.settings."asterisk.conf";
  in
    renderWith "asterisk.conf" (
      conf
      // {
        directories =
          conf.directories
          // lib.mapAttrs (_: dir: "@root@/${dir}") {
            astetcdir = "config";
            astrundir = "run";
            astvarlibdir = "lib";
            astdbdir = "lib";
            astkeydir = "lib";
            astspooldir = "lib/spool";
            astagidir = "lib/agi-bin";
            astlogdir = "log";
          };
        # the check runs as whoever builds it, where the asterisk user does
        # not exist
        options = removeAttrs (conf.options or {}) ["runuser" "rungroup"];
      }
    );
  # a certificate and its key in one file, so it works for any TLS file:
  # OpenSSL reads the part it needs
  checkCertificate = pkgs.runCommand "asterisk-check-certificate" {nativeBuildInputs = [pkgs.openssl];} ''
    openssl req -x509 -newkey ec -pkeyopt ec_paramgen_curve:P-256 -noenc -days 36500 \
      -subj /CN=asterisk-config-check -keyout key.pem -out cert.pem
    cat cert.pem key.pem > $out
  '';
  checkTree = pkgs.linkFarm "asterisk-check-config" (
    mapAttrsToList (file: text: {
      name = "config/${file}";
      path = configFile file (lib.replaceStrings ["${paths.credentials}/"] ["@root@/credentials/"] text);
    }) (
      cfg.renderedFiles
      # res_rtp_asterisk looks a STUN server's name up with Asterisk's own DNS
      # client (res_nsearch), which never reads the hosts file below
      // lib.optionalAttrs (stunName != null) {
        "rtp.conf" = lib.replaceStrings ["stunaddr = ${stunName}"] ["stunaddr = 192.0.2.1"] cfg.renderedFiles."rtp.conf";
      }
      // {
        "asterisk.conf" = checkAsteriskConf;
        "logger.conf" = format.render {syntax = syntaxFor "logger.conf";} {sections.logfiles.check = "error,warning,verbose";};
      }
    )
    ++ map (name: {
      name = "credentials/${name}";
      path = checkCertificate;
    }) (attrNames cfg.credentials)
    ++ optional (checkHostNames != []) {
      name = "hosts";
      path = pkgs.writeText "asterisk-check-hosts" (lib.concatMapStrings (name: "192.0.2.1 ${name}\n") checkHostNames);
    }
    # below @root@, with lib for the state directory
    ++ [
      {
        name = "directories";
        path = pkgs.writeText "asterisk-check-directories" (
          lib.concatMapStrings (dir: "${dir}\n") (["run" "log"] ++ map (dir: "lib/${dir}") stateDirectories)
        );
      }
    ]
  );
  # the host of `host:port` and whether it is a name, not an address
  hostOf = v: builtins.head (builtins.match "[[:space:]]*([^:/[:space:]]*).*" (toString v));
  isName = v: builtins.match "[A-Za-z0-9-]+([.][A-Za-z0-9-]+)*" v != null && builtins.match "[0-9.]+" v == null;
  stunName =
    if rtpGeneral ? stunaddr && isName (hostOf rtpGeneral.stunaddr)
    then hostOf rtpGeneral.stunaddr
    else null;
  # host names Asterisk resolves while it loads the configuration; the build
  # has no DNS, so for the check they resolve to a documentation address
  checkHostNames = let
    listOf = v:
      if builtins.isList v
      then v
      else lib.splitString "," (toString v);
    ofType = type: filter (s: (s.type or null) == type) pjsipObjects;
  in
    unique (filter isName (map hostOf (
      # every section's `match`, templates included: an identify resolves the
      # `match` lines it inherits as well as its own
      concatMap (s: listOf (s.match or [])) (attrValues (cfg.settings."pjsip.conf" or {}))
      ++ concatMap (s: lib.optionals (s ? external_signaling_address) [s.external_signaling_address] ++ lib.optionals (s ? external_media_address) [s.external_media_address]) (ofType "transport")
      ++ lib.optionals (rtpGeneral ? turnaddr) [rtpGeneral.turnaddr]
    )));
  # extraArguments as Asterisk's getopt reads them (main/asterisk.c
  # getopt_settings): { option; value; } for each option, { argument; } for the rest
  extraOptions = let
    takesValue = option: builtins.elem option ["C" "e" "G" "L" "M" "s" "U" "x"];
    add = acc: item: acc // {items = acc.items ++ [item];};
    cluster = acc: characters: let
      option = builtins.head characters;
      rest = lib.concatStrings (builtins.tail characters);
    in
      if characters == []
      then acc
      else if !(takesValue option)
      then
        cluster (add acc {
          inherit option;
          value = null;
        }) (builtins.tail characters)
      else if rest != ""
      then
        add acc {
          inherit option;
          value = rest;
        }
      else acc // {expecting = option;};
    step = acc: argument:
      if acc.expecting != null
      then
        add (acc // {expecting = null;}) {
          option = acc.expecting;
          value = argument;
        }
      else if acc.operands || argument == "-" || !(lib.hasPrefix "-" argument)
      then add acc {inherit argument;}
      else if argument == "--"
      then add (acc // {operands = true;}) {inherit argument;}
      else cluster acc (lib.stringToCharacters (lib.removePrefix "-" argument));
    parsed =
      lib.foldl' step {
        items = [];
        expecting = null;
        operands = false;
      }
      cfg.extraArguments;
  in
    parsed.items
    ++ optional (parsed.expecting != null) {
      option = parsed.expecting;
      value = null;
    };
  # extraArguments for the check, without the user and group of -U and -G,
  # which the build does not have (see checkAsteriskConf)
  checkExtraArguments =
    concatMap (
      item:
        if item ? argument
        then [item.argument]
        else if builtins.elem item.option ["U" "G"] && item.value != null
        then []
        else ["-${item.option}"] ++ optional (item.value != null) item.value
    )
    extraOptions;
  # the check's arguments are passed on for the probe (tests/campaign/probe.nix),
  # which boots Asterisk the same way
  checkArguments =
    optional (builtins.any lowPort listenPorts) "--low-ports"
    ++ concatMap (argument: ["--argument" argument]) checkExtraArguments
    ++ [
      asteriskBin
      "${checkTree}"
    ]
    ++ bindAddresses;
  configCheck = pkgs.runCommand "asterisk-config-check" {passthru.arguments = checkArguments;} ''
    ${lib.getExe (pkgs.callPackage ../pkgs/config-check/package.nix {})} ${lib.escapeShellArgs checkArguments} || {
      echo "(services.asterisk.checkConfig = false turns this check off)" >&2
      exit 1
    }
    touch $out
  '';

  # Every secret placeholder in the generated files, including secrets
  # interpolated into strings and placeholders written in extraConfig.
  refsByFile = lib.genAttrs fileNames (file: secrets.fromText cfg.renderedFiles.${file});
  secretRefs = unique (concatLists (attrValues refsByFile));
  filesWithSecrets = attrNames (filterAttrs (_: refs: refs != []) refsByFile);
  secretManifest = pkgs.writeText "asterisk-secrets" (secrets.manifest {
      fields = cfg.fieldSecrets;
      maxLengths = cfg.secretMaxLengths;
    }
    secretRefs);

  # Keys that hold credentials; a plain string there lands in the store.
  secretKeys = [
    "password"
    "password_digest"
    "md5_cred"
    "pin"
    "secret"
    "turnpassword"
  ];
  plainSecrets = concatMap (
    file:
      concatMap (
        id:
          map (key: ''settings."${file}"."${id}".${key}'') (
            filter (key: builtins.isString (cfg.settings.${file}.${id}.${key} or null)) secretKeys
          )
      ) (attrNames cfg.settings.${file})
  ) (attrNames cfg.settings);
  fileSecrets = filter (ref: ref ? _secret) secretRefs;

  # credentials whose path would change the lines of the unit: a line break
  # starts a line of its own, and a backslash at the end joins the next line
  # to its LoadCredential= line
  unitBreakingCredentials = attrNames (
    filterAttrs (_: path: lib.hasInfix "\n" path || lib.hasInfix "\r" path || hasSuffix "\\" path) cfg.credentials
  );

  # Asterisk skips a line of a config file longer than 8190 bytes (main/config.c
  # config_text_file_load); render-secrets checks a line with its secrets
  longLines = concatMap (
    file:
      concatLists (lib.imap1 (
        n: line:
          optional (
            builtins.stringLength line
            > 8190
            && builtins.stringLength (lib.concatStrings (filter builtins.isString (builtins.split secrets.placeholderPattern line))) > 8190
          ) "${file}, line ${toString n}: ${builtins.substring 0 32 line}..."
      ) (lib.splitString "\n" cfg.renderedFiles.${file}))
  ) (filter (hasSuffix ".conf") fileNames);

  # Parts of the configuration that Asterisk only reads at startup. Changing
  # them restarts the service; everything else is applied with a reload.
  pjsipObjects = (format.resolveInheritance (cfg.settings."pjsip.conf" or {})).sections;
  pjsipTransports = filter (s: (s.type or null) == "transport") pjsipObjects;
  restartOnlyConfig = builtins.hashString "sha256" (
    concatStringsSep "\n" (
      map renderFile (
        filter (f: builtins.elem f fileNames) [
          "asterisk.conf"
          "modules.conf"
        ]
      )
      ++ [(format.render {} {sections = lib.listToAttrs (map (t: lib.nameValuePair t.name t) pjsipTransports);})]
    )
  );

  # Files whose change is applied by a targeted reload; any other file falls
  # back to `core reload`. Only `module reload` reports a result, so every
  # targeted reload is one.
  reloadCommands = {
    "extensions.conf" = "module reload pbx_config.so";
    "pjsip.conf" = "module reload res_pjsip.so";
    "pjsip_notify.conf" = "module reload res_pjsip_notify.so";
    "rtp.conf" = "module reload res_rtp_asterisk.so";
    "logger.conf" = "module reload logger";
    "voicemail.conf" = "module reload app_voicemail.so";
    "confbridge.conf" = "module reload app_confbridge.so";
    "queues.conf" = "module reload app_queue.so";
    "queuerules.conf" = "module reload app_queue.so";
    "musiconhold.conf" = "module reload res_musiconhold.so";
    "features.conf" = "module reload features";
    "res_parking.conf" = "module reload res_parking.so";
    "manager.conf" = "module reload manager";
    "http.conf" = "module reload http";
    "ari.conf" = "module reload res_ari.so";
    "cdr.conf" = "module reload cdr";
    "cdr_custom.conf" = "module reload cdr_custom.so";
    "cdr_sqlite3_custom.conf" = "module reload cdr_sqlite3_custom.so";
    "cel.conf" = "module reload cel";
    "cel_custom.conf" = "module reload cel_custom.so";
    "cel_sqlite3_custom.conf" = "module reload cel_sqlite3_custom.so";
    "acl.conf" = "module reload acl";
    "indications.conf" = "module reload indications";
    "udptl.conf" = "module reload udptl";
  };
  restartOnlyFiles = [
    "asterisk.conf"
    "modules.conf"
  ];

  asteriskBin = "${cfg.package}/bin/asterisk";

  # files that name a credential Asterisk reads itself (a TLS key, ...), by
  # credential: a changed credential counts as a change of these files
  credentialFiles =
    lib.mapAttrs (
      name: _: filter (file: lib.hasInfix "${paths.credentials}/${name}" cfg.renderedFiles.${file}) fileNames
    )
    cfg.credentials;

  # Renders /etc/asterisk (store, placeholders) into /run/asterisk/config
  # (tmpfs, secrets substituted). Runs as the asterisk user inside the
  # sandbox; secrets arrive as systemd credentials.
  configTool = pkgs.writeShellApplication {
    name = "asterisk-config";
    runtimeInputs = with pkgs; [
      coreutils
      diffutils
      findutils
      gnugrep
      (callPackage ../pkgs/render-secrets/package.nix {})
    ];
    text = ''
      umask 0077

      mode=''${1:-start}
      template=${paths.template}
      runtime=${paths.runtime}
      current=${paths.config}

      new=$(mktemp -d "$runtime/.config.XXXXXXXX")
      cleanup() {
        if [ -n "$new" ] && [ -d "$new" ]; then
          chmod -R u+w "$new"
          rm -rf "$new"
        fi
      }
      trap cleanup EXIT

      cp -rL --no-preserve=mode,ownership,timestamps "$template/." "$new/"
      chmod -R u+w "$new"
      ${lib.optionalString (filesWithSecrets != []) ''
        (cd "$new" && render-secrets asterisk ${secretManifest} ${lib.escapeShellArgs filesWithSecrets})
      ''}
      if grep -rqF '@NIX_ASTERISK_SECRET:' "$new"; then
        echo "asterisk-config: unresolved secret placeholder in:" >&2
        grep -rlF '@NIX_ASTERISK_SECRET:' "$new" >&2
        exit 1
      fi

      find "$new" -type f -exec chmod 0400 {} +
      find "$new" -type d -exec chmod 0500 {} +

      changed=()
      if [ -d "$current/" ]; then
        while IFS= read -r -d "" file; do
          rel=''${file#"$new"/}
          cmp -s "$file" "$current/$rel" || changed+=("$rel")
        done < <(find "$new" -type f -print0)
        while IFS= read -r -d "" file; do
          rel=''${file#"$current"/}
          [ -e "$new/$rel" ] || changed+=("$rel")
        done < <(find "$current/" -type f -print0)
      fi
      ${lib.optionalString (cfg.credentials != {}) ''
        sums=$runtime/credentials.sha256
        (cd "$CREDENTIALS_DIRECTORY" && sha256sum -- ${lib.escapeShellArgs (attrNames cfg.credentials)}) > "$sums.new"
        if [ -f "$sums" ]; then
          while read -r _ name; do
            case $name in
              ${concatStringsSep "\n" (
          mapAttrsToList (name: files: "${lib.escapeShellArg name}) changed+=(${lib.escapeShellArgs files}) ;;") credentialFiles
        )}
            esac
          done < <(grep -vxFf "$sums" "$sums.new" || true)
        fi
      ''}
      # Atomically point $current at the new tree, then drop older trees.
      ln -sfn "$(basename "$new")" "$runtime/.config.link"
      mv -Tf "$runtime/.config.link" "$current"
      for dir in "$runtime"/.config.*; do
        if [ -d "$dir" ] && [ ! -L "$dir" ] && [ "$dir" != "$new" ]; then
          chmod -R u+w "$dir"
          rm -rf "$dir"
        fi
      done
      new=""
      ${lib.optionalString (cfg.credentials != {}) ''mv "$sums.new" "$sums"''}

      case $mode in
        start)
          mkdir -p ${lib.escapeShellArgs (map (dir: "${paths.state}/${dir}") stateDirectories)}
          ;;
        reload)
          declare -A commands=()
          for file in "''${changed[@]}"; do
            case $file in
              ${concatStringsSep "\n          " (
        mapAttrsToList (
          file: command: "${lib.escapeShellArg file}) commands[${lib.escapeShellArg command}]=1 ;;"
        )
        reloadCommands
      )}
              ${concatStringsSep " | " (map lib.escapeShellArg restartOnlyFiles)})
                echo "asterisk-config: $file changed; restart Asterisk to apply it" >&2 ;;
              *) commands["core reload"]=1 ;;
            esac
          done
          if [ -n "''${commands[core reload]:-}" ]; then
            commands=(["core reload"]=1)
          fi
          # asterisk -rx exits 0 whatever the command did; module reload says
          # whether the reload failed as a whole, core reload says nothing
          failed=0
          for command in "''${!commands[@]}"; do
            echo "asterisk-config: $command"
            output=$(${asteriskBin} -C "$current/asterisk.conf" -rx "$command")
            case $command in
              "module reload "*)
                module=''${command#module reload }
                if ! grep -qxF "Module '$module' reloaded successfully." <<< "$output"; then
                  echo "asterisk-config: $command failed: $output" >&2
                  failed=1
                fi
                ;;
            esac
          done
          exit "$failed"
          ;;
      esac
    '';
  };

  waitForAddresses = pkgs.writeShellScript "asterisk-wait-for-addresses" ''
    for address in ${lib.escapeShellArgs bindAddresses}; do
      waited=0
      until [ -n "$(${pkgs.iproute2}/bin/ip -o address show to "$address" -tentative)" ]; do
        if [ "$waited" -eq 0 ]; then
          echo "asterisk-config: waiting for address $address"
        elif [ "$waited" -ge 90 ]; then
          echo "asterisk-config: address $address is not configured on this host" >&2
          exit 1
        fi
        sleep 1
        waited=$((waited + 1))
      done
    done
  '';

  # nixpkgs builds asterisk without libsystemd, so its READY=1 is never sent
  # TODO: Type = "notify" instead, once https://github.com/NixOS/nixpkgs/blob/master/pkgs/servers/asterisk/default.nix has systemd in buildInputs
  waitForBoot = pkgs.writeShellScript "asterisk-wait-for-boot" ''
    for _ in $(seq 1 600); do
      [ -S ${paths.runtime}/asterisk.ctl ] && break
      sleep 0.2
    done
    exec ${asteriskBin} -C ${paths.config}/asterisk.conf -rx "core waitfullybooted"
  '';

  # `asterisk -rx "..."` for admins: always talks to the running daemon.
  cliWrapper = pkgs.writeShellApplication {
    name = "asterisk";
    text = ''
      # read the options as Asterisk's getopt does (main/asterisk.c), which
      # takes `-C -r` as a file named -r and stops at `--`; -r, -R and -x
      # connect to the daemon, -V and -h print and exit
      remote=0
      while getopts ":BC:cde:FfG:ghIiL:M:mnpqRrs:TtU:VvWXx:" option; do
        case $option in
          r | R | x) remote=1 ;;
          V | h) exec ${asteriskBin} "$@" ;;
          # any other option, unknown or missing its argument, decides nothing
          *) ;;
        esac
      done
      if [ "$remote" = 0 ]; then
        echo "asterisk: this wrapper only connects to the running daemon; use -r, -rvvv or -rx \"command\"." >&2
        echo "The daemon itself is managed by systemd: systemctl status asterisk" >&2
        exit 1
      fi
      exec ${asteriskBin} -C ${paths.template}/asterisk.conf "$@"
    '';
  };
  remoteConsole = pkgs.writeShellScriptBin "rasterisk" ''
    exec ${cliWrapper}/bin/asterisk -r "$@"
  '';

  # Ports derived from the (typed or freeform) configuration.
  parseBindPort = bind: default: let
    bracketed = builtins.match "[[].*[]]:([0-9]+)" bind;
    plain = builtins.match "[^:]*:([0-9]+)" bind;
  in
    if bracketed != null
    then lib.toInt (builtins.head bracketed)
    else if plain != null
    then lib.toInt (builtins.head plain)
    else default;

  transportPorts =
    map (
      t: let
        # Asterisk reads the protocol in any case (res_pjsip/config_transport.c)
        protocol = lib.toLower (t.protocol or "udp");
      in {
        inherit protocol;
        port = parseBindPort (toString (t.bind or "0.0.0.0")) (
          if protocol == "tls"
          then 5061
          else 5060
        );
      }
    )
    pjsipTransports;

  toPort = v:
    if builtins.isString v
    then lib.toInt v
    else v;

  rtpGeneral = cfg.settings."rtp.conf".general or {};
  rtpRange = {
    from = toPort (rtpGeneral.rtpstart or 5000);
    to = toPort (rtpGeneral.rtpend or 31000);
  };
  # Asterisk raises either end below 1024 to 1024 (res_rtp_asterisk.c,
  # MINIMUM_RTP_PORT). RTP takes even ports up to the end, the end included,
  # and RTCP the port above each, so an even end has its RTCP one past it.
  rtpPorts = let
    raised = lib.mapAttrs (_: lib.max 1024) rtpRange;
  in
    raised
    // {
      to = raised.to + 1 - lib.mod raised.to 2;
    };

  # Ports Asterisk binds at startup (not only the ones opened in the
  # firewall); one below 1024 needs CAP_NET_BIND_SERVICE. RTP ports are never
  # below 1024.
  httpGeneral = cfg.settings."http.conf".general or {};
  managerGeneral = cfg.settings."manager.conf".general or {};
  httpPorts =
    optional (format.isTrue (httpGeneral.enabled or false)) (toPort (httpGeneral.bindport or 8088))
    ++ optional (format.isTrue (httpGeneral.tlsenable or false)) (
      parseBindPort (toString (httpGeneral.tlsbindaddr or "0.0.0.0")) 8089
    );
  amiPorts = optional (format.isTrue (managerGeneral.enabled or false)) (toPort (managerGeneral.port or 5038));
  listenPorts = map (t: t.port) transportPorts ++ httpPorts ++ amiPorts;
  lowPort = port: port < 1024;
  needsLowPorts = builtins.any lowPort listenPorts;

  # Specific addresses Asterisk binds (not wildcard or loopback). With
  # scripted networking, static addresses of interfaces other than the default
  # gateway's are not ordered before network-online.target, and a transport
  # that fails to bind at startup stays down: the service waits for them.
  bindHost = bind: let
    bracketed = builtins.match "[[]([^]]+)[]](:[0-9]+)?" bind;
    ipv4 = builtins.match "([0-9.]+)(:[0-9]+)?" bind;
  in
    if bracketed != null
    then builtins.head bracketed
    else if ipv4 != null
    then builtins.head ipv4
    else bind;
  # an IPv4 address is four parts of 0 to 255; the check gives each one a
  # loopback address of its own, which would hide a value that is no address
  isAddress = a: let
    part = "(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])";
  in
    builtins.match "${part}([.]${part}){3}" a != null || lib.hasInfix ":" a;
  bindAddresses = unique (
    filter
    (
      a:
        isAddress a
        && !(builtins.elem a [
          "0.0.0.0"
          "::"
          "127.0.0.1"
          "::1"
        ])
    )
    (
      map (t: bindHost (toString (t.bind or "0.0.0.0"))) pjsipTransports
      ++ optional (format.isTrue (httpGeneral.enabled or false)) (toString (httpGeneral.bindaddr or "0.0.0.0"))
      ++ optional (format.isTrue (httpGeneral.tlsenable or false)) (
        bindHost (toString (httpGeneral.tlsbindaddr or "0.0.0.0"))
      )
      ++ optional (format.isTrue (managerGeneral.enabled or false)) (
        toString (managerGeneral.bindaddr or "0.0.0.0")
      )
    )
  );

  firewallPorts = {
    allowedUDPPorts = unique (
      map (t: t.port) (filter (t: t.protocol == "udp") transportPorts)
    );
    allowedTCPPorts = unique (
      map (t: t.port) (
        filter (
          t:
            builtins.elem t.protocol [
              "tcp"
              "tls"
            ]
        )
        transportPorts
      )
      ++ lib.optionals cfg.firewall.http httpPorts
      ++ lib.optionals cfg.firewall.ami amiPorts
    );
    allowedUDPPortRanges = [rtpPorts];
  };

  includeType = types.coercedTo types.str (file: {inherit file;}) (
    types.submodule {
      options = {
        file = mkOption {
          type = types.str;
          description = "File to include, relative to the configuration directory or absolute.";
        };
        optional = mkOption {
          type = types.bool;
          default = false;
          description = "Use `#tryinclude`, which does not fail if the file is missing.";
        };
      };
    }
  );

  syntaxType = types.submodule (
    {name, ...}: let
      defaults = format.syntaxFor name;
    in {
      options = {
        arrowKeys = mkOption {
          type = types.listOf types.str;
          default = defaults.arrowKeys;
          description = "Keys rendered as `key => value`.";
        };
        arrowSections = mkOption {
          type = types.listOf types.str;
          default = defaults.arrowSections;
          description = "Sections in which every key is rendered as `key => value`.";
        };
        keyOrder = mkOption {
          type = types.listOf types.str;
          default = defaults.keyOrder;
          description = "Keys rendered first, in this order; the rest follow alphabetically.";
        };
        compactExtensions = mkOption {
          type = types.bool;
          default = defaults.compactExtensions;
          description = "Render consecutive `exten` lines of one extension as `same =>`.";
        };
      };
    }
  );

  managedDirectories = {
    astetcdir = paths.config;
    astrundir = paths.runtime;
  };
in {
  options.services.asterisk = {
    enable = mkEnableOption "the Asterisk PBX, configured declaratively";

    package = mkPackageOption pkgs "asterisk" {};

    settings = mkOption {
      type = types.attrsOf format.types.sections;
      default = {};
      description = ''
        Freeform configuration for any Asterisk configuration file, keyed by
        file name and then by a unique section id. Each section has the
        options `name` (the Asterisk section name, defaulting to the id, so
        several sections can share a name), `order`, `template` and
        `inherits`; every other attribute is a key. Lists render as repeated
        keys, booleans as `yes`/`no`, and any value can be a secret reference
        (`config.lib.asterisk.secret config.sops.secrets.foo.path`).

        The typed options (`pjsip`, `dialplan`, ...) write into this option,
        so everything they generate can be extended or overridden here.
      '';
      example = literalExpression ''
        {
          "pjsip.conf" = {
            transport-udp = {
              type = "transport";
              protocol = "udp";
              bind = "0.0.0.0:5060";
            };
            alice = {
              type = "endpoint";
              context = "internal";
              disallow = "all";
              allow = [ "g722" "ulaw" ];
              auth = "alice";
              aors = "alice";
            };
            alice-auth = {
              name = "alice";
              type = "auth";
              username = "alice";
              password = config.lib.asterisk.secret config.sops.secrets.alice.path;
            };
            alice-aor = {
              name = "alice";
              type = "aor";
              max_contacts = 1;
            };
          };
        }
      '';
    };

    extraConfig = mkOption {
      type = types.attrsOf types.lines;
      default = {};
      description = ''
        Raw text appended to a configuration file, keyed by file name. It is
        not escaped, but secret references interpolated into it are
        substituted like in `settings`. Start it with a section header,
        otherwise it continues the last generated section.
      '';
      example = literalExpression ''
        {
          "extensions.conf" = '''
            [legacy]
            exten => 999,1,Playback(tt-monkeys)
          ''';
        }
      '';
    };

    includes = mkOption {
      type = types.attrsOf (types.listOf includeType);
      default = {};
      description = ''
        `#include` (or, with `optional = true`, `#tryinclude`) directives
        placed at the top of a configuration file, keyed by file name.
      '';
      example = literalExpression ''
        { "pjsip.conf" = [ { file = "/var/lib/asterisk/pjsip-local.conf"; optional = true; } ]; }
      '';
    };

    syntax = mkOption {
      type = types.attrsOf syntaxType;
      default = {};
      description = ''
        Per-file rendering conventions: which keys use `=>`, the key order and
        whether dialplan lines are compacted to `same =>`. Defaults follow
        Asterisk's sample configuration files.
      '';
    };

    credentials = mkOption {
      type = types.attrsOf types.str;
      default = {};
      description = ''
        Files passed to the service as systemd credentials (`LoadCredential=`),
        keyed by credential name. Asterisk can read them from
        `${paths.credentials}/<name>` even if the source file is only readable
        by root, which makes this the right place for TLS private keys.
      '';
      example = {
        "tls-key" = "/var/lib/acme/pbx.example.org/key.pem";
      };
    };

    reloadOnChange = mkOption {
      type = types.bool;
      default = true;
      description = ''
        Apply configuration changes on `nixos-rebuild switch` with a reload
        (targeted `module reload` commands, falling back to `core reload`)
        instead of a restart. Changes to the package,
        {file}`asterisk.conf`, {file}`modules.conf`, PJSIP transports or the
        set of secrets always restart the service.
      '';
    };

    checkConfig = mkOption {
      type = types.bool;
      default = pkgs.stdenv.buildPlatform.canExecute pkgs.stdenv.hostPlatform;
      defaultText = literalExpression "pkgs.stdenv.buildPlatform.canExecute pkgs.stdenv.hostPlatform";
      description = ''
        Start Asterisk with the generated configuration when the system is
        built, and fail the build if Asterisk logs an error or a warning
        while loading it, or if the dialplan uses an application, function
        or switch that no loaded module provides. Secrets are replaced by zeros,
        credentials by a throwaway certificate and IPv4 listen addresses by
        loopback ones, so a sandboxed build needs no privileges. Listening on
        IPv6 addresses or ports below 1024, or building without the sandbox,
        needs unprivileged user namespaces on the build machine, which some
        systems (Ubuntu 24.04) forbid. Files outside the Nix store that the
        configuration names do not exist there.

        Without the check, what Asterisk rejects only shows in its log. A
        reload that cannot create a PJSIP object still succeeds and keeps the
        object's previous version until the next start.
      '';
    };

    realtime = mkOption {
      type = types.bool;
      default = false;
      description = ''
        Run Asterisk with realtime scheduling (SCHED_RR, priority 10).
        Asterisk only raises its own priority when started as root, so the
        unit starts it with `CPUSchedulingPolicy=rr` instead of passing `-p`.
        Asterisk notices and runs its `astcanary` watchdog, which lowers the
        priority again if Asterisk starves the rest of the system.
      '';
    };

    extraArguments = mkOption {
      type = types.listOf types.str;
      default = [];
      example = ["-vvv"];
      description = ''
        Extra command line arguments for the Asterisk daemon. The build-time
        check ({option}`services.asterisk.checkConfig`) starts Asterisk with
        them too, except `-U` and `-G`, whose user and group the build does
        not have.
      '';
    };

    sounds.packages = mkOption {
      type = types.listOf types.path;
      default = [];
      example = literalExpression "[ (pkgs.callPackage ./asterisk-sounds-de.nix { }) ]";
      description = ''
        Directories merged into Asterisk's data directory (`astdatadir`), for
        example sound packages laid out as `sounds/<language>/...` or music on
        hold as `moh/...`. The package already ships the English core sounds
        (GSM) and the default music on hold; nixpkgs has no further Asterisk
        sound packages.
      '';
    };

    openFirewall = mkOption {
      type = types.bool;
      default = false;
      description = ''
        Open the ports Asterisk is configured to use: PJSIP transports (UDP
        for `udp`, TCP for `tcp`/`tls`), the RTP port range and any ports
        typed modules add (for example AMI or HTTP when their own
        `openFirewall` is set).
      '';
    };

    firewallInterfaces = mkOption {
      type = types.listOf types.str;
      default = [];
      example = [
        "lan"
        "voip"
      ];
      description = ''
        Interfaces on which {option}`services.asterisk.openFirewall`
        opens ports. Empty means all interfaces.
      '';
    };

    firewall = {
      http = mkOption {
        type = types.bool;
        default = false;
        internal = true;
        description = "Open the ports the HTTP server listens on, as http.conf sets them.";
      };
      ami = mkOption {
        type = types.bool;
        default = false;
        internal = true;
        description = "Open the port AMI listens on, as manager.conf sets it.";
      };
    };

    renderedFiles = mkOption {
      type = types.attrsOf types.str;
      readOnly = true;
      internal = true;
      description = "Text of every generated configuration file (with secret placeholders).";
    };

    fieldSecrets = mkOption {
      type = types.listOf (types.attrsOf types.str);
      default = [];
      internal = true;
      description = ''
        Secret references that are one field of a comma-separated value, from
        the modules that know the file's format. The service does not start
        when one of them contains a comma.
      '';
    };

    secretMaxLengths = mkOption {
      type = types.attrsOf types.ints.unsigned;
      default = {};
      internal = true;
      description = ''
        The most bytes Asterisk keeps of a secret, by its placeholder, from the
        modules that know the file's format. The service does not start when a
        secret is longer.
      '';
    };

    generatedConfig = mkOption {
      type = types.package;
      readOnly = true;
      description = ''
        The generated configuration directory (with secret placeholders), also
        linked to {file}`/etc/asterisk`.
      '';
    };

    paths = mkOption {
      type = types.attrsOf types.str;
      readOnly = true;
      description = "Directories used by the service.";
    };
  };

  config = mkMerge [
    # Helpers such as config.lib.asterisk.secret, available even when the
    # service is disabled.
    {lib.asterisk = asteriskLib;}

    (mkIf cfg.enable {
      services.asterisk = {
        inherit generatedConfig;
        renderedFiles = lib.genAttrs fileNames renderFile;
        paths =
          paths
          // {
            data = "${dataDir}";
          };
      };

      assertions =
        map (file: {
          assertion =
            builtins.match "[A-Za-z0-9_+-][A-Za-z0-9_.+-]*(/[A-Za-z0-9_+-][A-Za-z0-9_.+-]*)*" file != null;
          message = "services.asterisk: invalid configuration file name `${file}`.";
        })
        fileNames
        ++ map (ref: {
          assertion = !(secrets.isStorePath ref);
          message = ''
            services.asterisk: the secret file ${ref._secret} is in the
            Nix store, where every user can read it. Use sops-nix, or any other
            file outside the store.
          '';
        })
        fileSecrets
        ++ map (ref: {
          assertion = secrets.isValidReference ref;
          message =
            if ref ? _secret
            then "services.asterisk: secret path `${ref._secret}` must be absolute and only contain letters, digits and _.+/=-."
            else "services.asterisk: invalid systemd credential name `${ref._credential}`.";
        })
        secretRefs
        ++ mapAttrsToList (key: value: {
          assertion = (cfg.settings."asterisk.conf".directories.${key} or value) == value;
          message = "services.asterisk: asterisk.conf directories.${key} is managed by the module and must stay ${value}.";
        })
        managedDirectories
        ++ mapAttrsToList (name: _: {
          assertion = secrets.isValidCredentialName name && builtins.match "secret-.*" name == null;
          message = "services.asterisk.credentials: invalid or reserved credential name `${name}`.";
        })
        cfg.credentials
        ++ [
          {
            # the check cannot see it: Asterisk goes on in a process of its own
            assertion = !(builtins.any (item: (item.option or null) == "F") extraOptions);
            message = "services.asterisk.extraArguments: with -F Asterisk forks into the background, and systemd stops the service once the process it started has exited.";
          }
          {
            assertion = unitBreakingCredentials == [];
            message = "services.asterisk.credentials: paths cannot contain a line break or end with a backslash, which would change the lines of asterisk.service: ${concatStringsSep ", " unitBreakingCredentials}.";
          }
          {
            assertion = moduleLib.invalidInterfaces cfg.firewallInterfaces == [];
            message = "services.asterisk.firewallInterfaces: Linux takes interface names of 1 to 15 bytes without /, : or whitespace: ${
              lib.concatMapStringsSep ", " builtins.toJSON (moduleLib.invalidInterfaces cfg.firewallInterfaces)
            }.";
          }
          {
            # otherwise res_rtp_asterisk uses 5000-31000, which the firewall does not open
            assertion = rtpRange.from < rtpRange.to;
            message = "services.asterisk.rtp.portRange (rtpstart and rtpend in rtp.conf): `from` (${toString rtpRange.from}) must be lower than `to` (${toString rtpRange.to}).";
          }
          {
            assertion = longLines == [];
            message = ''
              services.asterisk: lines longer than 8190 bytes, which Asterisk skips:
                ${concatStringsSep "\n  " longLines}
            '';
          }
        ];

      warnings =
        map (
          path: "services.asterisk.${path} is a plain string, so it is stored world-readable in the Nix store; use config.lib.asterisk.secret \"/path/to/file\" instead."
        )
        plainSecrets
        ++ optional
        (
          (cfg.settings."extensions.conf" or {})
          != {}
          && builtins.any (s: s ? same) (attrValues cfg.settings."extensions.conf")
        )
        "services.asterisk: `same` keys in settings.\"extensions.conf\" render after all `exten` lines of their section; write complete `exten` lines instead (consecutive lines are printed as `same =>` automatically).";
    })

    (mkIf cfg.enable {
      # Built-in defaults have the lowest priority (mkOptionDefault), below the
      # mkDefault values of typed options and plain user definitions.
      services.asterisk.settings = {
        "asterisk.conf" = {
          directories = {
            order = 0;
            astetcdir = paths.config;
            astmoddir = "${cfg.package}/lib/asterisk/modules";
            astvarlibdir = paths.state;
            astdbdir = paths.state;
            astkeydir = paths.state;
            astdatadir = "${dataDir}";
            astagidir = mkOptionDefault "${paths.state}/agi-bin";
            astspooldir = paths.spool;
            astrundir = paths.runtime;
            astlogdir = paths.log;
            astsbindir = "${cfg.package}/sbin";
          };
          options = {
            order = 1;
            documentation_language = mkOptionDefault "en_US";
            hideconnect = mkOptionDefault true;
          };
          # The socket is created by the asterisk user and group already;
          # astctlowner/astctlgroup would need chown(2), which is filtered.
          files = {
            order = 2;
            astctlpermissions = mkOptionDefault "0660";
          };
        };

        # Minimal files for core subsystems, so Asterisk starts without
        # "unable to load config file" errors. All of them can be extended.
        "acl.conf" = {};
        "ccss.conf".general = {};
        "cdr.conf".general = {};
        "cel.conf".general = {};
        "features.conf".general = {};
        "pjproject.conf" = {};
        "stasis.conf" = {};
        "manager.conf".general.enabled = mkOptionDefault false;
        "udptl.conf".general = {};
        "confbridge.conf".general = {};
        "indications.conf".general.country = mkOptionDefault "us";
        "musiconhold.conf".default = {
          mode = mkOptionDefault "files";
          directory = mkOptionDefault "moh";
        };
      };

      # Tone zones and NOTIFY types shipped with the package.
      services.asterisk.extraConfig = {
        "indications.conf" = ''#include "${cfg.package}/etc/asterisk/indications.conf"'';
        "pjsip_notify.conf" = ''#include "${cfg.package}/etc/asterisk/pjsip_notify.conf"'';
      };

      environment.etc.asterisk.source = generatedConfig;

      system.checks = optional cfg.checkConfig configCheck;

      environment.systemPackages = [
        cliWrapper
        remoteConsole
      ];

      users.users.asterisk = {
        isSystemUser = true;
        uid = config.ids.uids.asterisk;
        group = "asterisk";
        home = paths.state;
        description = "Asterisk PBX daemon";
      };
      users.groups.asterisk.gid = config.ids.gids.asterisk;

      systemd.services.asterisk = {
        description = "Asterisk PBX";
        documentation = ["https://docs.asterisk.org/"];
        wantedBy = ["multi-user.target"];
        wants = ["network-online.target"];
        after = [
          "network-online.target"
          "time-sync.target"
        ];

        restartTriggers = [restartOnlyConfig] ++ optional (!cfg.reloadOnChange) generatedConfig;
        reloadTriggers = optional cfg.reloadOnChange generatedConfig;
        # Keep the old daemon running during activation and restart it
        # afterwards: shorter downtime.
        stopIfChanged = false;

        serviceConfig =
          {
            # exec, not simple: ExecStartPost= must not race the credential
            # setup of the main process
            Type = "exec";
            User = "asterisk";
            Group = "asterisk";
            ExecStartPre =
              optional (bindAddresses != []) "${waitForAddresses}"
              ++ [
                "${configTool}/bin/asterisk-config start"
              ];
            ExecStart = utils.escapeSystemdExecArgs (
              [
                asteriskBin
                "-f"
                "-n"
                "-C"
                "${paths.config}/asterisk.conf"
              ]
              ++ cfg.extraArguments
            );
            ExecStartPost = waitForBoot;
            ExecReload = "${configTool}/bin/asterisk-config reload";
            Restart = "on-failure";
            RestartSec = "5s";
            TimeoutStartSec = "5min";

            LoadCredential =
              map (ref: "${secrets.credentialName ref}:${ref._secret}") fileSecrets
              ++ mapAttrsToList (name: path: "${name}:${path}") cfg.credentials;

            RuntimeDirectory = "asterisk";
            RuntimeDirectoryMode = "0750";
            StateDirectory = "asterisk";
            StateDirectoryMode = "0750";
            # a list: modules add subdirectories (cdr-csv); Asterisk creates none
            LogsDirectory = ["asterisk"];
            LogsDirectoryMode = "0750";
            UMask = "0027";
            LimitNOFILE = 65536;
            # a core dump holds every secret Asterisk read; systemd-coredump
            # keeps none of a process whose RLIMIT_CORE is 0
            LimitCORE = 0;
            # Realtime scheduling is set by systemd: Asterisk ignores -p unless
            # it starts as root. LimitRTPRIO lets it adjust the priority later.
            CPUSchedulingPolicy = mkIf cfg.realtime "rr";
            CPUSchedulingPriority = mkIf cfg.realtime 10;
            LimitRTPRIO = mkIf cfg.realtime 10;

            # Hardening. Asterisk runs unprivileged from the start (no -U), so
            # it needs no capabilities unless a port below 1024 is bound.
            CapabilityBoundingSet =
              if needsLowPorts
              then ["CAP_NET_BIND_SERVICE"]
              else [""];
            AmbientCapabilities = mkIf needsLowPorts ["CAP_NET_BIND_SERVICE"];
            NoNewPrivileges = true;
            PrivateTmp = true;
            PrivateDevices = true;
            ProtectSystem = "strict";
            ProtectHome = true;
            ProtectKernelTunables = true;
            ProtectKernelModules = true;
            ProtectKernelLogs = true;
            ProtectControlGroups = true;
            ProtectClock = true;
            ProtectHostname = true;
            ProtectProc = "invisible";
            ProcSubset = "pid";
            RestrictAddressFamilies = [
              "AF_UNIX"
              "AF_INET"
              "AF_INET6"
              "AF_NETLINK"
            ];
            RestrictNamespaces = true;
            RestrictRealtime = !cfg.realtime;
            RestrictSUIDSGID = true;
            LockPersonality = true;
            MemoryDenyWriteExecute = true;
            RemoveIPC = true;
            SystemCallArchitectures = "native";
            # @chown: Asterisk always calls chown(2) on its control socket
            # (a no-op without CAP_CHOWN, but noisy when filtered).
            SystemCallFilter = [
              "@system-service"
              "~@privileged"
              "@chown"
            ];
            SystemCallErrorNumber = "EPERM";
          }
          // lib.optionalAttrs (lib.versionAtLeast config.systemd.package.version "260") {
            # Password rotation: `systemctl reload asterisk` re-reads secrets.
            RefreshOnReload = "credentials";
          };
      };

      networking.firewall = mkIf cfg.openFirewall (moduleLib.firewallOn cfg.firewallInterfaces firewallPorts);
    })
  ];
}
