# Core of services.asterisk-declarative: layer-1 freeform settings for every
# configuration file, runtime rendering of secrets, the systemd service with
# its hardening, state directories, the CLI wrapper and the firewall.
{
  config,
  lib,
  pkgs,
  utils,
  ...
}:
let
  inherit (lib)
    attrNames
    attrValues
    concatMap
    concatMapStringsSep
    concatStringsSep
    filter
    filterAttrs
    hasSuffix
    literalExpression
    mapAttrsToList
    mkEnableOption
    mkIf
    mkMerge
    mkOption
    mkOptionDefault
    mkPackageOption
    optional
    types
    unique
    ;

  cfg = config.services.asterisk-declarative;
  asteriskLib = import ../lib { inherit lib; };
  inherit (asteriskLib) format secrets;

  paths = {
    template = "/etc/asterisk";
    runtime = "/run/asterisk";
    config = "/run/asterisk/config";
    state = "/var/lib/asterisk";
    spool = "/var/lib/asterisk/spool";
    log = "/var/log/asterisk";
    credentials = "/run/credentials/asterisk.service";
  };

  # Read-only data: sounds, music on hold, documentation, static HTTP files.
  dataDir = pkgs.symlinkJoin {
    name = "asterisk-data";
    paths = [ "${cfg.package}/var/lib/asterisk" ] ++ cfg.sounds.packages;
  };

  fileNames = unique (
    attrNames cfg.settings
    ++ attrNames (filterAttrs (_: text: text != "") cfg.extraConfig)
    ++ attrNames (filterAttrs (_: incs: incs != [ ]) cfg.includes)
  );

  syntaxFor =
    file:
    if cfg.syntax ? ${file} then
      removeAttrs cfg.syntax.${file} [ "_module" ]
    else
      format.syntaxFor file;

  renderFile =
    file:
    format.render
      {
        syntax = syntaxFor file;
        inherit file;
        header =
          if hasSuffix ".conf" file then
            "Generated by NixOS (services.asterisk-declarative); changes will be overwritten."
          else
            null;
      }
      {
        sections = cfg.settings.${file} or { };
        includes = cfg.includes.${file} or [ ];
        extraConfig = cfg.extraConfig.${file} or "";
      };

  generatedConfig = pkgs.linkFarm "asterisk-config" (
    map (file: {
      name = file;
      path = pkgs.writeText "asterisk-${
        lib.replaceStrings [ "/" ] [ "-" ] file
      }" cfg.renderedFiles.${file};
    }) fileNames
  );

  # Every secret placeholder in the generated files, including secrets
  # interpolated into strings and placeholders written in extraConfig.
  secretRefs = unique (concatMap (file: secrets.fromText cfg.renderedFiles.${file}) fileNames);

  # Keys that hold credentials; a plain string there lands in the store.
  secretKeys = [
    "password"
    "password_digest"
    "md5_cred"
    "secret"
    "turnpassword"
  ];
  plainSecrets = concatMap (
    file:
    concatMap (
      id:
      map (key: ''settings."${file}"."${id}".${key}'') (
        filter (key: builtins.isString (cfg.settings.${file}.${id}.${key} or null)) secretKeys
      )
    ) (attrNames cfg.settings.${file})
  ) (attrNames cfg.settings);
  fileSecrets = filter (ref: ref ? _secret) secretRefs;

  # Parts of the configuration that Asterisk only reads at startup. Changing
  # them restarts the service; everything else is applied with a reload.
  pjsipTransports = filterAttrs (_: s: (s.type or null) == "transport") (
    cfg.settings."pjsip.conf" or { }
  );
  restartOnlyConfig = builtins.hashString "sha256" (
    concatStringsSep "\n" (
      map renderFile (
        filter (f: builtins.elem f fileNames) [
          "asterisk.conf"
          "modules.conf"
        ]
      )
      ++ [ (format.render { } { sections = pjsipTransports; }) ]
    )
  );

  # Files whose change is applied by a targeted reload; any other file falls
  # back to `core reload`.
  reloadCommands = {
    "extensions.conf" = "dialplan reload";
    "pjsip.conf" = "module reload res_pjsip.so";
    "pjsip_notify.conf" = "module reload res_pjsip_notify.so";
    "rtp.conf" = "module reload res_rtp_asterisk.so";
    "logger.conf" = "logger reload";
    "voicemail.conf" = "module reload app_voicemail.so";
    "confbridge.conf" = "module reload app_confbridge.so";
    "queues.conf" = "module reload app_queue.so";
    "queuerules.conf" = "module reload app_queue.so";
    "musiconhold.conf" = "module reload res_musiconhold.so";
    "features.conf" = "module reload features";
    "res_parking.conf" = "module reload res_parking.so";
    "manager.conf" = "module reload manager";
    "http.conf" = "module reload http";
    "ari.conf" = "module reload res_ari.so";
    "cdr.conf" = "module reload cdr";
    "cdr_custom.conf" = "module reload cdr_custom.so";
    "cdr_sqlite3_custom.conf" = "module reload cdr_sqlite3_custom.so";
    "cel.conf" = "module reload cel";
    "cel_custom.conf" = "module reload cel_custom.so";
    "cel_sqlite3_custom.conf" = "module reload cel_sqlite3_custom.so";
    "acl.conf" = "module reload acl";
    "indications.conf" = "module reload indications";
    "udptl.conf" = "module reload udptl";
  };
  restartOnlyFiles = [
    "asterisk.conf"
    "modules.conf"
  ];

  asteriskBin = "${cfg.package}/bin/asterisk";

  # Renders /etc/asterisk (store, placeholders) into /run/asterisk/config
  # (tmpfs, secrets substituted). Runs as the asterisk user inside the
  # sandbox; secrets arrive as systemd credentials.
  configTool = pkgs.writeShellApplication {
    name = "asterisk-config";
    runtimeInputs = with pkgs; [
      coreutils
      diffutils
      findutils
      gnugrep
    ];
    text = ''
      shopt -u patsub_replacement 2>/dev/null || true
      umask 0077

      mode=''${1:-start}
      template=${paths.template}
      runtime=${paths.runtime}
      current=${paths.config}
      escaped_semicolon='\;'

      new=$(mktemp -d "$runtime/.config.XXXXXXXX")
      cleanup() {
        if [ -n "$new" ] && [ -d "$new" ]; then
          chmod -R u+w "$new"
          rm -rf "$new"
        fi
      }
      trap cleanup EXIT

      cp -rL --no-preserve=mode,ownership,timestamps "$template/." "$new/"
      chmod -R u+w "$new"

      substitute() {
        local placeholder=$1 credential=$2 source=$3 value file content
        local path="''${CREDENTIALS_DIRECTORY:-/nonexistent}/$credential"
        if [ ! -f "$path" ]; then
          echo "asterisk-config: secret $source (credential $credential) is not available" >&2
          return 1
        fi
        value=$(< "$path")
        value=''${value%$'\r'}
        case $value in
          *$'\n'* | *$'\r'*)
            echo "asterisk-config: secret $source contains a line break" >&2
            return 1
            ;;
          [[:space:]]* | *[[:space:]])
            echo "asterisk-config: secret $source has leading or trailing whitespace, which Asterisk config files cannot represent" >&2
            return 1
            ;;
        esac
        value=''${value//;/"$escaped_semicolon"}
        while IFS= read -r -d "" file; do
          content=$(< "$file")
          printf '%s\n' "''${content//"$placeholder"/"$value"}" > "$file"
        done < <(grep -rlFZ -- "$placeholder" "$new" || true)
      }

      ${concatMapStringsSep "\n" (
        ref:
        "substitute ${
          lib.escapeShellArgs [
            (secrets.placeholder ref)
            (secrets.credentialName ref)
            (ref._secret or "credential ${ref._credential}")
          ]
        }"
      ) secretRefs}

      if grep -rqF '@NIX_ASTERISK_SECRET:' "$new"; then
        echo "asterisk-config: unresolved secret placeholder in:" >&2
        grep -rlF '@NIX_ASTERISK_SECRET:' "$new" >&2
        exit 1
      fi

      find "$new" -type f -exec chmod 0400 {} +
      find "$new" -type d -exec chmod 0500 {} +

      changed=()
      if [ -d "$current/" ]; then
        while IFS= read -r -d "" file; do
          rel=''${file#"$new"/}
          cmp -s "$file" "$current/$rel" || changed+=("$rel")
        done < <(find "$new" -type f -print0)
        while IFS= read -r -d "" file; do
          rel=''${file#"$current"/}
          [ -e "$new/$rel" ] || changed+=("$rel")
        done < <(find "$current/" -type f -print0)
      fi

      # Atomically point $current at the new tree, then drop older trees.
      ln -sfn "$(basename "$new")" "$runtime/.config.link"
      mv -Tf "$runtime/.config.link" "$current"
      for dir in "$runtime"/.config.*; do
        if [ -d "$dir" ] && [ ! -L "$dir" ] && [ "$dir" != "$new" ]; then
          chmod -R u+w "$dir"
          rm -rf "$dir"
        fi
      done
      new=""

      case $mode in
        start)
          mkdir -p ${paths.state}/agi-bin ${paths.state}/keys
          for dir in voicemail monitor recording outgoing tmp meetme dictate system; do
            mkdir -p "${paths.spool}/$dir"
          done
          ;;
        reload)
          declare -A commands=()
          for file in "''${changed[@]}"; do
            case $file in
              ${concatStringsSep "\n          " (
                mapAttrsToList (
                  file: command: "${lib.escapeShellArg file}) commands[${lib.escapeShellArg command}]=1 ;;"
                ) reloadCommands
              )}
              ${concatStringsSep " | " (map lib.escapeShellArg restartOnlyFiles)})
                echo "asterisk-config: $file changed; restart Asterisk to apply it" >&2 ;;
              *) commands["core reload"]=1 ;;
            esac
          done
          if [ -n "''${commands[core reload]:-}" ]; then
            commands=(["core reload"]=1)
          fi
          for command in "''${!commands[@]}"; do
            echo "asterisk-config: $command"
            ${asteriskBin} -C "$current/asterisk.conf" -rx "$command"
          done
          ;;
      esac
    '';
  };

  waitForBoot = pkgs.writeShellScript "asterisk-wait-for-boot" ''
    for _ in $(seq 1 600); do
      [ -S ${paths.runtime}/asterisk.ctl ] && break
      sleep 0.2
    done
    exec ${asteriskBin} -C ${paths.config}/asterisk.conf -rx "core waitfullybooted"
  '';

  # `asterisk -rx "..."` for admins: always talks to the running daemon.
  cliWrapper = pkgs.writeShellApplication {
    name = "asterisk";
    text = ''
      remote=0
      for arg in "$@"; do
        case $arg in
          --*) ;;
          -*[rR]*) remote=1 ;;
        esac
      done
      if [ "$remote" = 0 ]; then
        case ''${1:-} in
          -V | -h) exec ${asteriskBin} "$@" ;;
        esac
        echo "asterisk: this wrapper only connects to the running daemon; use -r, -rvvv or -rx \"command\"." >&2
        echo "The daemon itself is managed by systemd: systemctl status asterisk" >&2
        exit 1
      fi
      exec ${asteriskBin} -C ${paths.template}/asterisk.conf "$@"
    '';
  };
  remoteConsole = pkgs.writeShellScriptBin "rasterisk" ''
    exec ${cliWrapper}/bin/asterisk -r "$@"
  '';

  # Ports derived from the (typed or freeform) configuration.
  parseBindPort =
    bind: default:
    let
      bracketed = builtins.match "[[].*[]]:([0-9]+)" bind;
      plain = builtins.match "[^:]*:([0-9]+)" bind;
    in
    if bracketed != null then
      lib.toInt (builtins.head bracketed)
    else if plain != null then
      lib.toInt (builtins.head plain)
    else
      default;

  transportPorts = mapAttrsToList (
    _: t:
    let
      protocol = t.protocol or "udp";
    in
    {
      inherit protocol;
      port = parseBindPort (toString (t.bind or "0.0.0.0")) (if protocol == "tls" then 5061 else 5060);
    }
  ) pjsipTransports;

  toPort = v: if builtins.isString v then lib.toInt v else v;

  rtpGeneral = cfg.settings."rtp.conf".general or { };
  rtpRange = {
    from = toPort (rtpGeneral.rtpstart or 5000);
    to = toPort (rtpGeneral.rtpend or 31000);
  };

  # Ports Asterisk binds itself (not only the ones opened in the firewall);
  # anything below 1024 needs CAP_NET_BIND_SERVICE.
  truthy = v: v == true || v == "yes";
  httpGeneral = cfg.settings."http.conf".general or { };
  managerGeneral = cfg.settings."manager.conf".general or { };
  boundPorts =
    map (t: t.port) transportPorts
    ++ [ rtpRange.from ]
    ++ optional (truthy (httpGeneral.enabled or false)) (toPort (httpGeneral.bindport or 8088))
    ++ optional (truthy (httpGeneral.tlsenable or false)) (
      parseBindPort (toString (httpGeneral.tlsbindaddr or "0.0.0.0")) 8089
    )
    ++ optional (truthy (managerGeneral.enabled or false)) (toPort (managerGeneral.port or 5038))
    ++ cfg.firewall.tcpPorts
    ++ cfg.firewall.udpPorts;
  needsLowPorts = builtins.any (port: port < 1024) boundPorts;

  firewallPorts = {
    allowedUDPPorts = unique (
      map (t: t.port) (filter (t: t.protocol == "udp") transportPorts) ++ cfg.firewall.udpPorts
    );
    allowedTCPPorts = unique (
      map (t: t.port) (
        filter (
          t:
          builtins.elem t.protocol [
            "tcp"
            "tls"
          ]
        ) transportPorts
      )
      ++ cfg.firewall.tcpPorts
    );
    allowedUDPPortRanges = [ rtpRange ] ++ cfg.firewall.udpPortRanges;
  };

  includeType = types.coercedTo types.str (file: { inherit file; }) (
    types.submodule {
      options = {
        file = mkOption {
          type = types.str;
          description = "File to include, relative to the configuration directory or absolute.";
        };
        optional = mkOption {
          type = types.bool;
          default = false;
          description = "Use `#tryinclude`, which does not fail if the file is missing.";
        };
      };
    }
  );

  syntaxType = types.submodule (
    { name, ... }:
    let
      defaults = format.syntaxFor name;
    in
    {
      options = {
        arrowKeys = mkOption {
          type = types.listOf types.str;
          default = defaults.arrowKeys;
          description = "Keys rendered as `key => value`.";
        };
        arrowSections = mkOption {
          type = types.listOf types.str;
          default = defaults.arrowSections;
          description = "Sections in which every key is rendered as `key => value`.";
        };
        keyOrder = mkOption {
          type = types.listOf types.str;
          default = defaults.keyOrder;
          description = "Keys rendered first, in this order; the rest follow alphabetically.";
        };
        compactExtensions = mkOption {
          type = types.bool;
          default = defaults.compactExtensions;
          description = "Render consecutive `exten` lines of one extension as `same =>`.";
        };
      };
    }
  );

  portRangeType = types.submodule {
    options = {
      from = mkOption {
        type = types.port;
        description = "First port of the range.";
      };
      to = mkOption {
        type = types.port;
        description = "Last port of the range.";
      };
    };
  };

  managedDirectories = {
    astetcdir = paths.config;
    astrundir = paths.runtime;
  };
in
{
  options.services.asterisk-declarative = {
    enable = mkEnableOption "the Asterisk PBX, configured declaratively";

    package = mkPackageOption pkgs "asterisk" { };

    settings = mkOption {
      type = types.attrsOf format.types.sections;
      default = { };
      description = ''
        Freeform configuration for any Asterisk configuration file, keyed by
        file name and then by a unique section id. Each section has the
        options `name` (the Asterisk section name, defaulting to the id, so
        several sections can share a name), `order`, `template` and
        `inherits`; every other attribute is a key. Lists render as repeated
        keys, booleans as `yes`/`no`, and any value can be a secret reference
        (`config.lib.asterisk.secret "/run/agenix/foo"`).

        The typed options (`pjsip`, `dialplan`, ...) write into this option,
        so everything they generate can be extended or overridden here.
      '';
      example = literalExpression ''
        {
          "pjsip.conf" = {
            transport-udp = {
              type = "transport";
              protocol = "udp";
              bind = "0.0.0.0:5060";
            };
            alice = {
              type = "endpoint";
              context = "internal";
              disallow = "all";
              allow = [ "g722" "ulaw" ];
              auth = "alice";
              aors = "alice";
            };
            alice-auth = {
              name = "alice";
              type = "auth";
              username = "alice";
              password = config.lib.asterisk.secret "/run/agenix/alice";
            };
            alice-aor = {
              name = "alice";
              type = "aor";
              max_contacts = 1;
            };
          };
        }
      '';
    };

    extraConfig = mkOption {
      type = types.attrsOf types.lines;
      default = { };
      description = ''
        Raw text appended to a configuration file, keyed by file name. It is
        not escaped and cannot contain secret references. Start it with a
        section header, otherwise it continues the last generated section.
      '';
      example = literalExpression ''
        {
          "extensions.conf" = '''
            [legacy]
            exten => 999,1,Playback(tt-monkeys)
          ''';
        }
      '';
    };

    includes = mkOption {
      type = types.attrsOf (types.listOf includeType);
      default = { };
      description = ''
        `#include` (or, with `optional = true`, `#tryinclude`) directives
        placed at the top of a configuration file, keyed by file name.
      '';
      example = literalExpression ''
        { "pjsip.conf" = [ { file = "/var/lib/asterisk/pjsip-local.conf"; optional = true; } ]; }
      '';
    };

    syntax = mkOption {
      type = types.attrsOf syntaxType;
      default = { };
      description = ''
        Per-file rendering conventions: which keys use `=>`, the key order and
        whether dialplan lines are compacted to `same =>`. Defaults follow
        Asterisk's sample configuration files.
      '';
    };

    credentials = mkOption {
      type = types.attrsOf types.str;
      default = { };
      description = ''
        Files passed to the service as systemd credentials (`LoadCredential=`),
        keyed by credential name. Asterisk can read them from
        `${paths.credentials}/<name>` even if the source file is only readable
        by root, which makes this the right place for TLS private keys.
      '';
      example = {
        "tls-key" = "/var/lib/acme/pbx.example.org/key.pem";
      };
    };

    reloadOnChange = mkOption {
      type = types.bool;
      default = true;
      description = ''
        Apply configuration changes on `nixos-rebuild switch` with a reload
        (targeted `module reload` / `dialplan reload` commands, falling back
        to `core reload`) instead of a restart. Changes to the package,
        {file}`asterisk.conf`, {file}`modules.conf`, PJSIP transports or the
        set of secrets always restart the service.
      '';
    };

    realtime = mkOption {
      type = types.bool;
      default = false;
      description = ''
        Run Asterisk with realtime scheduling (`asterisk -p`). The unit gets
        `LimitRTPRIO=` instead of `CAP_SYS_NICE`.
      '';
    };

    extraArguments = mkOption {
      type = types.listOf types.str;
      default = [ ];
      example = [ "-vvv" ];
      description = "Extra command line arguments for the Asterisk daemon.";
    };

    sounds.packages = mkOption {
      type = types.listOf types.path;
      default = [ ];
      example = literalExpression "[ (pkgs.callPackage ./asterisk-sounds-de.nix { }) ]";
      description = ''
        Directories merged into Asterisk's data directory (`astdatadir`), for
        example sound packages laid out as `sounds/<language>/...` or music on
        hold as `moh/...`. The package already ships the English core sounds
        (GSM) and the default music on hold; nixpkgs has no further Asterisk
        sound packages.
      '';
    };

    openFirewall = mkOption {
      type = types.bool;
      default = false;
      description = ''
        Open the ports Asterisk is configured to use: PJSIP transports (UDP
        for `udp`, TCP for `tcp`/`tls`), the RTP port range and any ports
        typed modules add (for example AMI or HTTP when their own
        `openFirewall` is set).
      '';
    };

    firewallInterfaces = mkOption {
      type = types.listOf types.str;
      default = [ ];
      example = [
        "lan"
        "voip"
      ];
      description = ''
        Interfaces on which {option}`services.asterisk-declarative.openFirewall`
        opens ports. Empty means all interfaces.
      '';
    };

    firewall = {
      tcpPorts = mkOption {
        type = types.listOf types.port;
        default = [ ];
        internal = true;
        description = "Additional TCP ports to open, contributed by typed modules.";
      };
      udpPorts = mkOption {
        type = types.listOf types.port;
        default = [ ];
        internal = true;
        description = "Additional UDP ports to open, contributed by typed modules.";
      };
      udpPortRanges = mkOption {
        type = types.listOf portRangeType;
        default = [ ];
        internal = true;
        description = "Additional UDP port ranges to open, contributed by typed modules.";
      };
    };

    renderedFiles = mkOption {
      type = types.attrsOf types.str;
      readOnly = true;
      internal = true;
      description = "Text of every generated configuration file (with secret placeholders).";
    };

    generatedConfig = mkOption {
      type = types.package;
      readOnly = true;
      description = ''
        The generated configuration directory (with secret placeholders), also
        linked to {file}`/etc/asterisk`.
      '';
    };

    paths = mkOption {
      type = types.attrsOf types.str;
      readOnly = true;
      description = "Directories used by the service.";
    };
  };

  config = mkMerge [
    # Helpers such as config.lib.asterisk.secret, available even when the
    # service is disabled.
    { lib.asterisk = asteriskLib; }

    (mkIf cfg.enable {
      services.asterisk-declarative = {
        inherit generatedConfig;
        renderedFiles = lib.genAttrs fileNames renderFile;
        paths = paths // {
          data = "${dataDir}";
        };
      };

      assertions = [
        {
          assertion = !config.services.asterisk.enable;
          message = ''
            services.asterisk-declarative and services.asterisk cannot be enabled
            together: both manage the `asterisk` user, the `asterisk.service`
            unit and /etc/asterisk. Disable services.asterisk.
          '';
        }
      ]
      ++ map (file: {
        assertion =
          builtins.match "[A-Za-z0-9_+-][A-Za-z0-9_.+-]*(/[A-Za-z0-9_+-][A-Za-z0-9_.+-]*)*" file != null;
        message = "services.asterisk-declarative: invalid configuration file name `${file}`.";
      }) fileNames
      ++ map (ref: {
        assertion = !(secrets.isStorePath ref);
        message = ''
          services.asterisk-declarative: the secret file ${ref._secret} is in the
          Nix store, where every user can read it. Use agenix, sops-nix or
          another file outside the store.
        '';
      }) fileSecrets
      ++ map (ref: {
        assertion = secrets.isValidReference ref;
        message =
          if ref ? _secret then
            "services.asterisk-declarative: secret path `${ref._secret}` must be absolute and only contain letters, digits and _.+/=-."
          else
            "services.asterisk-declarative: invalid systemd credential name `${ref._credential}`.";
      }) secretRefs
      ++ mapAttrsToList (key: value: {
        assertion = (cfg.settings."asterisk.conf".directories.${key} or value) == value;
        message = "services.asterisk-declarative: asterisk.conf directories.${key} is managed by the module and must stay ${value}.";
      }) managedDirectories
      ++ mapAttrsToList (name: _: {
        assertion = secrets.isValidCredentialName name && builtins.match "secret-.*" name == null;
        message = "services.asterisk-declarative.credentials: invalid or reserved credential name `${name}`.";
      }) cfg.credentials
      ++ map (range: {
        assertion = range.from <= range.to;
        message = "services.asterisk-declarative: invalid UDP port range ${toString range.from}-${toString range.to}.";
      }) firewallPorts.allowedUDPPortRanges;

      warnings =
        map (
          path:
          "services.asterisk-declarative.${path} is a plain string, so it is stored world-readable in the Nix store; use config.lib.asterisk.secret \"/path/to/file\" instead."
        ) plainSecrets
        ++
          optional
            (
              (cfg.settings."extensions.conf" or { }) != { }
              && builtins.any (s: s ? same) (attrValues cfg.settings."extensions.conf")
            )
            "services.asterisk-declarative: `same` keys in settings.\"extensions.conf\" render after all `exten` lines of their section; write complete `exten` lines instead (consecutive lines are printed as `same =>` automatically).";
    })

    # Everything below is skipped when the upstream module is enabled too, so
    # the assertion above is reported instead of conflicting definitions.
    (mkIf (cfg.enable && !config.services.asterisk.enable) {
      # Built-in defaults have the lowest priority (mkOptionDefault), below the
      # mkDefault values of typed options and plain user definitions.
      services.asterisk-declarative.settings = {
        "asterisk.conf" = {
          directories = {
            order = 0;
            astetcdir = paths.config;
            astmoddir = "${cfg.package}/lib/asterisk/modules";
            astvarlibdir = paths.state;
            astdbdir = paths.state;
            astkeydir = paths.state;
            astdatadir = "${dataDir}";
            astagidir = mkOptionDefault "${paths.state}/agi-bin";
            astspooldir = paths.spool;
            astrundir = paths.runtime;
            astlogdir = paths.log;
            astsbindir = "${cfg.package}/sbin";
          };
          options = {
            order = 1;
            documentation_language = mkOptionDefault "en_US";
            hideconnect = mkOptionDefault true;
          };
          # The socket is created by the asterisk user and group already;
          # astctlowner/astctlgroup would need chown(2), which is filtered.
          files = {
            order = 2;
            astctlpermissions = mkOptionDefault "0660";
          };
        };

        # Minimal files for core subsystems, so Asterisk starts without
        # "unable to load config file" errors. All of them can be extended.
        "acl.conf" = { };
        "ccss.conf".general = { };
        "cdr.conf".general = { };
        "cel.conf".general = { };
        "features.conf".general = { };
        "pjproject.conf" = { };
        "stasis.conf" = { };
        "manager.conf".general.enabled = mkOptionDefault false;
        "udptl.conf".general = { };
        "confbridge.conf".general = { };
        "indications.conf".general.country = mkOptionDefault "us";
        "musiconhold.conf".default = {
          mode = mkOptionDefault "files";
          directory = mkOptionDefault "moh";
        };
      };

      # Tone zones and NOTIFY types shipped with the package.
      services.asterisk-declarative.extraConfig = {
        "indications.conf" = ''#include "${cfg.package}/etc/asterisk/indications.conf"'';
        "pjsip_notify.conf" = ''#include "${cfg.package}/etc/asterisk/pjsip_notify.conf"'';
      };

      environment.etc.asterisk.source = generatedConfig;

      environment.systemPackages = [
        cliWrapper
        remoteConsole
      ];

      users.users.asterisk = {
        isSystemUser = true;
        uid = config.ids.uids.asterisk;
        group = "asterisk";
        home = paths.state;
        description = "Asterisk PBX daemon";
      };
      users.groups.asterisk.gid = config.ids.gids.asterisk;

      systemd.services.asterisk = {
        description = "Asterisk PBX";
        documentation = [ "https://docs.asterisk.org/" ];
        wantedBy = [ "multi-user.target" ];
        wants = [ "network-online.target" ];
        after = [
          "network-online.target"
          "time-sync.target"
        ];

        restartTriggers = [ restartOnlyConfig ] ++ optional (!cfg.reloadOnChange) generatedConfig;
        reloadTriggers = optional cfg.reloadOnChange generatedConfig;
        # Keep the old daemon running during activation and restart it
        # afterwards: shorter downtime.
        stopIfChanged = false;

        serviceConfig = {
          # exec, not simple: ExecStartPost= must not race the credential
          # setup of the main process
          Type = "exec";
          User = "asterisk";
          Group = "asterisk";
          ExecStartPre = "${configTool}/bin/asterisk-config start";
          ExecStart = utils.escapeSystemdExecArgs (
            [
              asteriskBin
              "-f"
              "-n"
              "-C"
              "${paths.config}/asterisk.conf"
            ]
            ++ optional cfg.realtime "-p"
            ++ cfg.extraArguments
          );
          ExecStartPost = waitForBoot;
          ExecReload = "${configTool}/bin/asterisk-config reload";
          Restart = "on-failure";
          RestartSec = "5s";
          TimeoutStartSec = "5min";

          LoadCredential =
            map (ref: "${secrets.credentialName ref}:${ref._secret}") fileSecrets
            ++ mapAttrsToList (name: path: "${name}:${path}") cfg.credentials;

          RuntimeDirectory = "asterisk";
          RuntimeDirectoryMode = "0750";
          StateDirectory = "asterisk";
          StateDirectoryMode = "0750";
          LogsDirectory = "asterisk";
          LogsDirectoryMode = "0750";
          UMask = "0027";
          LimitNOFILE = 65536;
          LimitRTPRIO = mkIf cfg.realtime 10;

          # Hardening. Asterisk runs unprivileged from the start (no -U), so
          # it needs no capabilities unless a port below 1024 is bound.
          CapabilityBoundingSet = if needsLowPorts then [ "CAP_NET_BIND_SERVICE" ] else [ "" ];
          AmbientCapabilities = mkIf needsLowPorts [ "CAP_NET_BIND_SERVICE" ];
          NoNewPrivileges = true;
          PrivateTmp = true;
          PrivateDevices = true;
          ProtectSystem = "strict";
          ProtectHome = true;
          ProtectKernelTunables = true;
          ProtectKernelModules = true;
          ProtectKernelLogs = true;
          ProtectControlGroups = true;
          ProtectClock = true;
          ProtectHostname = true;
          ProtectProc = "invisible";
          ProcSubset = "pid";
          RestrictAddressFamilies = [
            "AF_UNIX"
            "AF_INET"
            "AF_INET6"
            "AF_NETLINK"
          ];
          RestrictNamespaces = true;
          RestrictRealtime = !cfg.realtime;
          RestrictSUIDSGID = true;
          LockPersonality = true;
          MemoryDenyWriteExecute = true;
          RemoveIPC = true;
          SystemCallArchitectures = "native";
          # @chown: Asterisk always calls chown(2) on its control socket
          # (a no-op without CAP_CHOWN, but noisy when filtered).
          SystemCallFilter = [
            "@system-service"
            "~@privileged"
            "@chown"
          ];
          SystemCallErrorNumber = "EPERM";
        }
        // lib.optionalAttrs (lib.versionAtLeast config.systemd.package.version "260") {
          # Password rotation: `systemctl reload asterisk` re-reads secrets.
          RefreshOnReload = "credentials";
        };
      };

      networking.firewall = mkIf cfg.openFirewall (
        if cfg.firewallInterfaces == [ ] then
          firewallPorts
        else
          { interfaces = lib.genAttrs cfg.firewallInterfaces (_: firewallPorts); }
      );
    })
  ];
}
