# The cases sample.nix leaves out of the gate, with why: what the last whole
# run of options.py found wrong, and invalid values only a build check
# rejects, since the gate boots valid values only. options.py writes this
# file to OUT/known.nix.
{
  "pbx.hours.<name>.timezone = \"Mars/Olympus_Mons\"" = "rejected by pbx-hours-timezones";
  "services.asterisk.ami.address = \"127.0.0.1:5038\"" = "rejected by asterisk-config-check";
  "services.asterisk.ami.address = \"300.0.0.1\"" = "rejected by asterisk-config-check";
  "services.asterisk.ami.address = \"pbx\"" = "rejected by asterisk-config-check";
  "services.asterisk.ami.settings = {\"q7unknown\":\"x\"}" = "P3: loads";
  "services.asterisk.ami.users.<name>.permit = [\"10.0.0.0/33\"]" = "rejected by asterisk-config-check";
  "services.asterisk.ami.users.<name>.permit = [\"pbx\"]" = "rejected by asterisk-config-check";
  "services.asterisk.ami.users.<name>.read = [\"q7class\"]" = "P3: loads";
  "services.asterisk.ami.users.<name>.settings = {\"q7unknown\":\"x\"}" = "P3: loads";
  "services.asterisk.ami.users.<name>.write = [\"q7class\"]" = "P3: loads";
  "services.asterisk.ari.settings = {\"q7unknown\":\"x\"}" = "P3: loads";
  "services.asterisk.cdr.csv.settings = {\"q7unknown\":\"x\"}" = "P3: loads";
  "services.asterisk.cdr.settings = {\"q7unknown\":\"x\"}" = "rejected by asterisk-config-check";
  "services.asterisk.cdr.sqlite.table = \"\"" = "rejected by asterisk-config-check";
  "services.asterisk.cel.events = [\"Q7_EVENT\"]" = "rejected by asterisk-config-check";
  "services.asterisk.cel.sqlite.table = \"\"" = "rejected by asterisk-config-check";
  "services.asterisk.confbridge.bridges.<name>.maxMembers = 4294967296" = "P2: does not load";
  "services.asterisk.confbridge.bridges.<name>.maxMembers = 9223372036854775807" = "P2: does not load";
  "services.asterisk.confbridge.bridges.<name>.musicOnHoldClass = \"default\"" = "P2: does not load";
  "services.asterisk.confbridge.bridges.<name>.settings = {\"q7unknown\":\"x\"}" = "rejected by asterisk-config-check";
  "services.asterisk.confbridge.menus = {\"admin_menu\":{\"*1\":\"q7action\"}}" = "P3: loads";
  "services.asterisk.confbridge.users.<name>.settings = {\"q7unknown\":\"x\"}" = "rejected by asterisk-config-check";
  "services.asterisk.dialplan.contexts.<name>.extensions = {\"100\":[\"Dial(PJSIP/101\"]}" = "rejected by asterisk-config-check";
  "services.asterisk.dialplan.contexts.<name>.extensions = {\"100\":[\"Q7NoSuchApp(x)\"]}" = "rejected by asterisk-config-check";
  "services.asterisk.dialplan.contexts.<name>.extensions = {\"100\":[\"q7notanapp\"]}" = "rejected by asterisk-config-check";
  "services.asterisk.dialplan.contexts.<name>.hints = {\"101\":\"Q7Tech/101\"}" = "P3: loads";
  "services.asterisk.dialplan.general = {\"q7unknown\":\"x\"}" = "P3: loads";
  "services.asterisk.extraArguments = [\"--q7-no-such-option\"]" = "rejected by asterisk-config-check";
  "services.asterisk.extraConfig = {\"pjsip.conf\":\"[q7]\\ntype = q7type\\n\"}" = "P3: loads";
  "services.asterisk.features.applications.<name>.app = \"Q7NoSuchApp\"" = "P3: loads";
  "services.asterisk.features.applications.<name>.dtmf = \"q7\"" = "P3: loads";
  "services.asterisk.features.featureMap = {\"blindxfer\":\"q7\"}" = "P3: loads";
  "services.asterisk.features.featureMap = {\"q7feature\":\"*1\"}" = "rejected by asterisk-config-check";
  "services.asterisk.features.general = {\"q7unknown\":\"x\"}" = "rejected by asterisk-config-check";
  "services.asterisk.http.address = \"300.0.0.1\"" = "rejected by asterisk-config-check";
  "services.asterisk.http.address = \"pbx\"" = "rejected by asterisk-config-check";
  "services.asterisk.http.settings = {\"q7unknown\":\"x\"}" = "rejected by asterisk-config-check";
  "services.asterisk.http.tls.address = \"pbx\"" = "rejected by asterisk-config-check";
  "services.asterisk.includes.<name>.*.optional = default" = "limitation (the included file is not in the build)";
  "services.asterisk.includes.<name>.*.optional = false" = "limitation (the included file is not in the build)";
  "services.asterisk.logger.channels = {\"messages\":[\"q7level\"]}" = "P3: loads";
  "services.asterisk.modules.autoload = true" = "P2: does not load";
  "services.asterisk.modules.defaultModules = false" = "rejected by asterisk-config-check";
  "services.asterisk.modules.load = [\"q7_no_such_module.so\"]" = "rejected by asterisk-modules-check";
  "services.asterisk.modules.noload = [\"res_pjsip.so\"]" = "rejected by asterisk-config-check";
  "services.asterisk.modules.preload = [\"q7_no_such_module.so\"]" = "rejected by asterisk-modules-check";
  "services.asterisk.musicOnHold.classes.<name>.application = \"<store>/coreutils-9.11/bin/cat /dev/zero\" with services.asterisk.musicOnHold.classes.office.mode" = "P2: does not load";
  "services.asterisk.musicOnHold.classes.<name>.directory = \"q7-no-such-directory\"" = "rejected by asterisk-config-check";
  "services.asterisk.musicOnHold.classes.<name>.mode = \"custom\" with services.asterisk.musicOnHold.classes.office.application" = "P2: does not load";
  "services.asterisk.musicOnHold.classes.<name>.settings = {\"q7unknown\":\"x\"}" = "P3: loads";
  "services.asterisk.pjsip.acls.<name>.contactDeny = [\"q7net\"]" = "rejected by asterisk-config-check";
  "services.asterisk.pjsip.acls.<name>.contactPermit = [\"q7net\"]" = "rejected by asterisk-config-check";
  "services.asterisk.pjsip.acls.<name>.deny = [\"10.0.0.0/33\"]" = "rejected by asterisk-config-check";
  "services.asterisk.pjsip.acls.<name>.deny = [\"q7net\"]" = "rejected by asterisk-config-check";
  "services.asterisk.pjsip.acls.<name>.permit = [\"q7net\"]" = "rejected by asterisk-config-check";
  "services.asterisk.pjsip.acls.<name>.settings = {\"q7unknown\":\"x\"}" = "rejected by asterisk-config-check";
  "services.asterisk.pjsip.endpoints.<name>.allow = [\"q7codec\"]" = "rejected by asterisk-config-check";
  "services.asterisk.pjsip.endpoints.<name>.aor.contacts = [\"q7 contact\"]" = "rejected by asterisk-config-check";
  "services.asterisk.pjsip.endpoints.<name>.aor.maxContacts = 4294967296" = "P2: does not load";
  "services.asterisk.pjsip.endpoints.<name>.aor.maxContacts = 9223372036854775807" = "P2: does not load";
  "services.asterisk.pjsip.endpoints.<name>.aor.qualifyFrequency = 2147483647" = "P2: does not load";
  "services.asterisk.pjsip.endpoints.<name>.aor.qualifyFrequency = 2147483648" = "P2: does not load";
  "services.asterisk.pjsip.endpoints.<name>.aor.qualifyFrequency = 4294967296" = "P2: does not load";
  "services.asterisk.pjsip.endpoints.<name>.aor.qualifyFrequency = 9223372036854775807" = "P2: does not load";
  "services.asterisk.pjsip.endpoints.<name>.aor.settings = {\"q7unknown\":\"x\"}" = "rejected by asterisk-config-check";
  "services.asterisk.pjsip.endpoints.<name>.auth.settings = {\"q7unknown\":\"x\"}" = "rejected by asterisk-config-check";
  "services.asterisk.pjsip.endpoints.<name>.identify.match = [\"q7 host\"]" = "rejected by asterisk-config-check";
  "services.asterisk.pjsip.endpoints.<name>.identify.match = []" = "rejected by asterisk-config-check";
  "services.asterisk.pjsip.endpoints.<name>.identify.match = default" = "rejected by asterisk-config-check";
  "services.asterisk.pjsip.endpoints.<name>.identify.settings = {\"q7unknown\":\"x\"}" = "rejected by asterisk-config-check";
  "services.asterisk.pjsip.endpoints.<name>.mailboxes = [\"102@default\"]" = "P3: loads";
  "services.asterisk.pjsip.endpoints.<name>.outboundAuth.settings = {\"q7unknown\":\"x\"}" = "rejected by asterisk-config-check";
  "services.asterisk.pjsip.endpoints.<name>.settings = {\"q7unknown\":\"x\"}" = "rejected by asterisk-config-check";
  "services.asterisk.pjsip.endpoints.<name>.settings = {\"rtp_timeout\":0.5}" = "rejected by asterisk-config-check";
  "services.asterisk.pjsip.global = {\"q7unknown\":\"x\"}" = "rejected by asterisk-config-check";
  "services.asterisk.pjsip.system = {\"q7unknown\":\"x\"}" = "rejected by asterisk-config-check";
  "services.asterisk.pjsip.transports.<name>.address = \"10.0.0.1:5060\"" = "rejected by asterisk-config-check";
  "services.asterisk.pjsip.transports.<name>.address = \"300.0.0.1\"" = "rejected by asterisk-config-check";
  "services.asterisk.pjsip.transports.<name>.address = \"pbx\"" = "rejected by asterisk-config-check";
  "services.asterisk.pjsip.transports.<name>.externalMediaAddress = \"q7 address\"" = "rejected by asterisk-config-check";
  "services.asterisk.pjsip.transports.<name>.externalSignalingAddress = \"q7 address\"" = "rejected by asterisk-config-check";
  "services.asterisk.pjsip.transports.<name>.localNet = [\"q7net\"]" = "rejected by asterisk-config-check";
  "services.asterisk.pjsip.transports.<name>.settings = {\"q7unknown\":\"x\"}" = "rejected by asterisk-config-check";
  "services.asterisk.pjsip.trunks.<name>.allow = [\"q7codec\"]" = "rejected by asterisk-config-check";
  "services.asterisk.pjsip.trunks.<name>.aorSettings = {\"q7unknown\":\"x\"}" = "rejected by asterisk-config-check";
  "services.asterisk.pjsip.trunks.<name>.host = \"\"" = "rejected by asterisk-config-check";
  "services.asterisk.pjsip.trunks.<name>.host = \"q7 host\"" = "rejected by asterisk-config-check";
  "services.asterisk.pjsip.trunks.<name>.identify = null" = "P2: rejected at T0";
  "services.asterisk.pjsip.trunks.<name>.identify.match = [\"q7 host\"]" = "rejected by asterisk-config-check";
  "services.asterisk.pjsip.trunks.<name>.identify.settings = {\"q7unknown\":\"x\"}" = "rejected by asterisk-config-check";
  "services.asterisk.pjsip.trunks.<name>.outboundAuth.settings = {\"q7unknown\":\"x\"}" = "rejected by asterisk-config-check";
  "services.asterisk.pjsip.trunks.<name>.qualifyFrequency = 2147483647" = "P2: does not load";
  "services.asterisk.pjsip.trunks.<name>.qualifyFrequency = 2147483648" = "P2: does not load";
  "services.asterisk.pjsip.trunks.<name>.qualifyFrequency = 4294967296" = "P2: does not load";
  "services.asterisk.pjsip.trunks.<name>.qualifyFrequency = 9223372036854775807" = "P2: does not load";
  "services.asterisk.pjsip.trunks.<name>.registration.expiration = 4294967296" = "P2: does not load";
  "services.asterisk.pjsip.trunks.<name>.registration.expiration = 9223372036854775807" = "P2: does not load";
  "services.asterisk.pjsip.trunks.<name>.registration.retryInterval = 4294967296" = "P2: does not load";
  "services.asterisk.pjsip.trunks.<name>.registration.retryInterval = 9223372036854775807" = "P2: does not load";
  "services.asterisk.pjsip.trunks.<name>.registration.settings = {\"q7unknown\":\"x\"}" = "rejected by asterisk-config-check";
  "services.asterisk.pjsip.trunks.<name>.settings = {\"q7unknown\":\"x\"}" = "rejected by asterisk-config-check";
  "services.asterisk.queues.queues.<name>.members = [\"q7member\"]" = "rejected by asterisk-config-check";
  "services.asterisk.queues.queues.<name>.members.*.interface = \"q7member\"" = "rejected by asterisk-config-check";
  "services.asterisk.queues.queues.<name>.settings = {\"q7unknown\":\"x\"}" = "rejected by asterisk-config-check";
  "services.asterisk.rtp.portRange.from = 10001" = "P2: does not load";
  "services.asterisk.rtp.settings = {\"q7unknown\":\"x\"}" = "P3: loads";
  "services.asterisk.rtp.stunServer = \"q7 host\"" = "rejected by asterisk-config-check";
  "services.asterisk.settings = {\"acl.conf\":{\"office\":{\"q7unknown\":true}}}" = "rejected by asterisk-config-check";
  "services.asterisk.settings = {\"asterisk.conf\":{\"options\":{\"maxcalls\":0.5}}}" = "P3: loads";
  "services.asterisk.settings = {\"asterisk.conf\":{\"options\":{\"q7unknown\":true}}}" = "P3: loads";
  "services.asterisk.settings = {\"ccss.conf\":{\"general\":{\"q7unknown\":true}}}" = "P3: loads";
  "services.asterisk.settings = {\"cdr.conf\":{\"general\":{\"q7unknown\":true}}}" = "rejected by asterisk-config-check";
  "services.asterisk.settings = {\"cel.conf\":{\"general\":{\"q7unknown\":true}}}" = "rejected by asterisk-config-check";
  "services.asterisk.settings = {\"confbridge.conf\":{\"general\":{\"q7unknown\":true}}}" = "rejected by asterisk-config-check";
  "services.asterisk.settings = {\"extensions.conf\":{\"general\":{\"q7unknown\":true}}}" = "P3: loads";
  "services.asterisk.settings = {\"features.conf\":{\"general\":{\"q7unknown\":true}}}" = "rejected by asterisk-config-check";
  "services.asterisk.settings = {\"http.conf\":{\"general\":{\"q7unknown\":true}}}" = "rejected by asterisk-config-check";
  "services.asterisk.settings = {\"indications.conf\":{\"general\":{\"q7unknown\":true}}}" = "P3: loads";
  "services.asterisk.settings = {\"logger.conf\":{\"general\":{\"q7unknown\":true}}}" = "P3: loads";
  "services.asterisk.settings = {\"manager.conf\":{\"general\":{\"q7unknown\":true}}}" = "P3: loads";
  "services.asterisk.settings = {\"musiconhold.conf\":{\"default\":{\"q7unknown\":true}}}" = "P3: loads";
  "services.asterisk.settings = {\"pjsip.conf\":{\"endpoint:101\":{\"q7unknown\":true}}}" = "rejected by asterisk-config-check";
  "services.asterisk.settings = {\"pjsip.conf\":{\"endpoint:101\":{\"rtp_timeout\":0.5}}}" = "rejected by asterisk-config-check";
  "services.asterisk.settings = {\"queues.conf\":{\"general\":{\"q7unknown\":true}}} with services.asterisk.modules.load" = "P3: loads";
  "services.asterisk.settings = {\"rtp.conf\":{\"general\":{\"q7unknown\":true}}}" = "P3: loads";
  "services.asterisk.settings = {\"udptl.conf\":{\"general\":{\"q7unknown\":true}}}" = "rejected by asterisk-config-check";
  "services.asterisk.settings = {\"voicemail.conf\":{\"general\":{\"q7unknown\":true}}} with services.asterisk.voicemail.enable" = "P3: loads";
  "services.asterisk.settings.<name>.<name>.inherits = [\"nowhere\"]" = "rejected by asterisk-config-check";
  "services.asterisk.voicemail.format = [\"q7format\"]" = "rejected by asterisk-config-check";
  "services.asterisk.voicemail.mailboxes.<name>.options = {\"q7option\":true}" = "P3: loads";
  "services.asterisk.voicemail.maxMessages = 2147483647" = "P2: does not load";
  "services.asterisk.voicemail.maxMessages = 2147483648" = "P2: does not load";
  "services.asterisk.voicemail.maxMessages = 9223372036854775807" = "P2: does not load";
  "services.asterisk.voicemail.settings = {\"q7unknown\":\"x\"}" = "P3: loads";
}
